### ISSUE TITLE
want contribute language indonesian

### ISSUE THREAD

**Issue by GarudaID** [Team-Inceptus/Novaconomy#22]
### Feature Type

Other

### Description of Feature

I want to contribute to the Nova Economy plugin, but in the `language` section, where are the files located?

**Comment by GamerCoder215** [comment]
> ### Feature Type
> Other
> 
> ### Description of Feature
> I want to contribute to the Nova Economy plugin, but in the `language` section, where are the files located?

Thanks for wanting to contribute!

All of the language files are stored in the [plugin resources(https://github.com/Team-Inceptus/Novaconomy/tree/master/plugin/src/main/resources)](https://github.com/Team-Inceptus/Novaconomy/tree/master/plugin/src/main/resources) folder. All of the language files end in `.properties` (novaconomy.properties is the default english), with the language code as a prefix (i.e. `novaconomy-ja.properties` is Japanese).

Due to file encoding restrictions, languages with mostly non-Latin roots are encoded because they aren't compatible with UTF-8, the default file encoding standard. Thus, they are shown as characters like `\u00ED`. You can visualize these better with [IntelliJ](https://www.jetbrains.com/idea/)'s resource bundle editor (which is what I recommend for contributing) and enabling `native-to-ascii` conversions for typing/pasting in translations.
