### ISSUE TITLE
Novaeconomy stills signals as 1.6.2 

### ISSUE THREAD

**Issue by SimpleWayx** [Team-Inceptus/Novaconomy#50]
### Bug Type

Other Unexpected Behavior

### Minecraft Version

1.19.2

### Description

There is a minor issue with 1.6.2.1. Seems that in the server details mentions the recommendation to update.
Either is a small mistake or is just the previous version please look it up.

### Steps to Reproduce

Install new version given in Spigot.
Server mentions that stills 1.6.2

### Expected Behavior

Everything runs as is supposed to be.

### Actual Behavior

Throws 1.6.2 warning.

### Additional Info

Arclight Server (Plugins+Forge)

**Comment by GamerCoder215** [comment]
Setting the version to `1.6.2.1` was really only used because Spigot wouldn't update the download button to the new JAR unless I changed the version.

I get that the indicator can be annoying, but there's not really a point in updating the version inside the `plugin.yml` if it won't change anything.
